### ISSUE TITLE
May need to set shouldRetry to false

### ISSUE THREAD

**Issue by Mathbl** [tylerjroach/RuntimePermissionsExample#1]
Hi,

First of all, thanks for the example. It's a good way to unclutter permissions' code.

I encounter an issue with the following case:
- Select "Refuse" from the Android permission' dialog
- Select "Retry" from the retry dialog
- Select "Accept" from the Android permission' dialog

Then, the retry dialog shows up again, because onResume was called and shouldRetry was still true. I added this at the end of onRequestPermissionsResult to solve this case:

``` java
} else {
    shouldRetry = false;
    return;
}
```

**Comment by tylerjroach** [comment]
@Mathbl Nice catch! I fixed the issue in a slightly different way: https://github.com/tylerjroach/RuntimePermissionsExample/commit/d21f6fb15c10855178a028aca961053d1f7fa097. With the else statement in the for loop, you may end up assigning shouldRetry to false when it shouldn't be false (This will happen if you had denied the first permission and accepted the last).

**Comment by Mathbl** [comment]
Indeed, your fix is better. I only had one permission to accept for my case, so I didn't think further. Thanks!
