### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wistein** [tylerjroach/RuntimePermissionsExample#2]
I would like to take part of the RuntimePermissionsExample code for own apps which would be published in F-Droid. These apps are licensed under the Apache License, Version 2.0.

Alas for the RuntimePermissionsExample you don't give license info.

So unfortunately, I cannot make use of it.
Would be nice to have dedicated info on this.

Greetings,
wistein

**Comment by tylerjroach** [comment]
I'll add MIT license momentarily

**Comment by tylerjroach** [comment]
@wistein Feel free to use any of the code as you wish. I've licensed it under MIT, which is even less restrictive than Apache 2.0

**Comment by wistein** [comment]
Thanks a lot.
